<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Malkari" failures="15" tests="52" name="Runner.TestRunner" time="318.408" errors="3" timestamp="2025-05-10T15:07:09 MST" skipped="0">
  <testcase classname="Runner.TestRunner" name="runScenario" time="4.922"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="5.087"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="15.170">
    <failure message="No Practise Questions found expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Practise Questions found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at StepDefinitions.LinkeListStep.the_user_should_be_redirected_to_the_practice_page(LinkeListStep.java:164)
at ✽.The user should be redirected to the Practice page(file:///C:/Users/sunda/eclipse-workspace/ClubNinjas1_DS_Algo_project/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:272)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="4.934"/>
  <testcase classname="Runner.TestRunner" name="tearDownClass" time="0.044">
    <error message="No enum constant com.aventstack.chaintest.domain.Result.PENDING" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: No enum constant com.aventstack.chaintest.domain.Result.PENDING
at java.base/java.lang.Enum.valueOf(Enum.java:293)
at com.aventstack.chaintest.domain.Result.valueOf(Result.java:5)
at com.aventstack.chaintest.domain.Test.complete(Test.java:331)
at com.aventstack.chaintest.domain.Test.complete(Test.java:316)
at com.aventstack.chaintest.plugins.ChainTestCucumberListener.lambda$new$3(ChainTestCucumberListener.java:120)
at io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPublisher.java:51)
at io.cucumber.core.eventbus.AbstractEventPublisher.sendAll(AbstractEventPublisher.java:36)
at io.cucumber.core.plugin.CanonicalOrderEventPublisher.handle(CanonicalOrderEventPublisher.java:18)
at io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPublisher.java:44)
at io.cucumber.core.eventbus.AbstractEventBus.send(AbstractEventBus.java:12)
at io.cucumber.core.runtime.SynchronizedEventBus.send(SynchronizedEventBus.java:47)
at io.cucumber.core.runtime.CucumberExecutionContext.emitTestRunFinished(CucumberExecutionContext.java:117)
at io.cucumber.core.runtime.CucumberExecutionContext.finishTestRun(CucumberExecutionContext.java:104)
at io.cucumber.testng.TestNGCucumberRunner.finish(TestNGCucumberRunner.java:148)
at io.cucumber.testng.AbstractTestNGCucumberTests.tearDownClass(AbstractTestNGCucumberTests.java:57)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassConfigurations(TestMethodWorker.java:238)
at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:223)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- tearDownClass -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="5.018"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="4.794"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="4.673"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="0.103">
    <error message="Duplicate step definitions in StepDefinitions.ArrayPageStep.the_user_is_on_the_home_page_and_clicks_sign_in() and StepDefinitions.StackPageStep.The_user_is_on_the_Home_page_and_clicks_Sign_In()" type="io.cucumber.core.runner.DuplicateStepDefinitionException">
      <![CDATA[io.cucumber.core.runner.DuplicateStepDefinitionException: Duplicate step definitions in StepDefinitions.ArrayPageStep.the_user_is_on_the_home_page_and_clicks_sign_in() and StepDefinitions.StackPageStep.The_user_is_on_the_Home_page_and_clicks_Sign_In()
at io.cucumber.core.runner.CachingGlue.lambda$prepareGlue$3(CachingGlue.java:313)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at io.cucumber.core.runner.CachingGlue.prepareGlue(CachingGlue.java:307)
at io.cucumber.core.runner.Runner.runPickle(Runner.java:73)
at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:135)
at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:136)
at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:136)
at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:132)
at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="4.332"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="14.308">
    <failure message="No Practise Questions found expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Practise Questions found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at StepDefinitions.LinkeListStep.the_user_should_be_redirected_to_the_practice_page(LinkeListStep.java:164)
at ✽.The user should be redirected to the Practice page(file:///C:/Users/sunda/eclipse-workspace/ClubNinjas1_DS_Algo_project/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:200)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="4.815"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="5.227">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.LinkeListStep.the_user_should_able_to_see_a_error_message_from_excel_sheet_and_the(LinkeListStep.java:142)
at ✽.The user should able to see a error message from excel sheet "TryCode" and the  1(file:///C:/Users/sunda/eclipse-workspace/ClubNinjas1_DS_Algo_project/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:35)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="6.826">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.LinkeListStep.the_user_should_able_to_see_a_error_message_from_excel_sheet_and_the(LinkeListStep.java:142)
at ✽.The user should able to see a error message from excel sheet "TryCode" and the  1(file:///C:/Users/sunda/eclipse-workspace/ClubNinjas1_DS_Algo_project/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:252)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="4.870"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="5.294">
    <error message="TODO: implement me" type="io.cucumber.java.PendingException">
      <![CDATA[io.cucumber.java.PendingException: TODO: implement me
at StepDefinitions.LinkeListStep.the_user_should_be_redirected_to_deletion_page(LinkeListStep.java:401)
at ✽.The user should be redirected to  Deletion page(file:///C:/Users/sunda/eclipse-workspace/ClubNinjas1_DS_Algo_project/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:242)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="4.758"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="4.504"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="4.462"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="10.757"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="3.994"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="14.368">
    <failure message="No Practise Questions found expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Practise Questions found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at StepDefinitions.LinkeListStep.the_user_should_be_redirected_to_the_practice_page(LinkeListStep.java:164)
at ✽.The user should be redirected to the Practice page(file:///C:/Users/sunda/eclipse-workspace/ClubNinjas1_DS_Algo_project/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:126)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="4.579"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="4.751">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.LinkeListStep.the_user_should_able_to_see_a_error_message_from_excel_sheet_and_the(LinkeListStep.java:142)
at ✽.The user should able to see a error message from excel sheet "TryCode" and the  1(file:///C:/Users/sunda/eclipse-workspace/ClubNinjas1_DS_Algo_project/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:106)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="14.360">
    <failure message="No Practise Questions found expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Practise Questions found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at StepDefinitions.LinkeListStep.the_user_should_be_redirected_to_the_practice_page(LinkeListStep.java:164)
at ✽.The user should be redirected to the Practice page(file:///C:/Users/sunda/eclipse-workspace/ClubNinjas1_DS_Algo_project/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:161)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="5.038"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="13.921">
    <failure message="No Practise Questions found expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Practise Questions found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at StepDefinitions.LinkeListStep.the_user_should_be_redirected_to_the_practice_page(LinkeListStep.java:164)
at ✽.The user should be redirected to the Practice page(file:///C:/Users/sunda/eclipse-workspace/ClubNinjas1_DS_Algo_project/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:91)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="4.131">
    <failure message="expected [Creating Linked List] but found [Creating Linked LIst]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Creating Linked List] but found [Creating Linked LIst]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at StepDefinitions.LinkeListStep.the_user_should_be_redirected_to_creating_linked_list_page(LinkeListStep.java:182)
at ✽.The user should be redirected to Creating Linked list page(file:///C:/Users/sunda/eclipse-workspace/ClubNinjas1_DS_Algo_project/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:61)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="6.461"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="4.927"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="14.267">
    <failure message="No Practise Questions found expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Practise Questions found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at StepDefinitions.LinkeListStep.the_user_should_be_redirected_to_the_practice_page(LinkeListStep.java:164)
at ✽.The user should be redirected to the Practice page(file:///C:/Users/sunda/eclipse-workspace/ClubNinjas1_DS_Algo_project/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:56)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="4.999">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.LinkeListStep.the_user_should_able_to_see_a_error_message_from_excel_sheet_and_the(LinkeListStep.java:142)
at ✽.The user should able to see a error message from excel sheet "TryCode" and the  1(file:///C:/Users/sunda/eclipse-workspace/ClubNinjas1_DS_Algo_project/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:141)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="5.014"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="4.655"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="4.864"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="4.045"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="5.018"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="3.872"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="4.142"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="3.971"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="4.782">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.LinkeListStep.the_user_should_able_to_see_a_error_message_from_excel_sheet_and_the(LinkeListStep.java:142)
at ✽.The user should able to see a error message from excel sheet "TryCode" and the  1(file:///C:/Users/sunda/eclipse-workspace/ClubNinjas1_DS_Algo_project/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:71)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="5.073">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.LinkeListStep.the_user_should_able_to_see_a_error_message_from_excel_sheet_and_the(LinkeListStep.java:142)
at ✽.The user should able to see a error message from excel sheet "TryCode" and the  1(file:///C:/Users/sunda/eclipse-workspace/ClubNinjas1_DS_Algo_project/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:178)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="5.007"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="4.953"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="4.616"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="6.391"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="5.505"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="6.750"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="4.994"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="5.000"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="5.037">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.LinkeListStep.the_user_should_able_to_see_a_error_message_from_excel_sheet_and_the(LinkeListStep.java:142)
at ✽.The user should able to see a error message from excel sheet "TryCode" and the  1(file:///C:/Users/sunda/eclipse-workspace/ClubNinjas1_DS_Algo_project/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:216)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="14.025">
    <failure message="No Practise Questions found expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Practise Questions found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at StepDefinitions.LinkeListStep.the_user_should_be_redirected_to_the_practice_page(LinkeListStep.java:164)
at ✽.The user should be redirected to the Practice page(file:///C:/Users/sunda/eclipse-workspace/ClubNinjas1_DS_Algo_project/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:237)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Runner.TestRunner -->
